"""add sync change feed

Revision ID: 73a64f0afdcc
Revises: 815c2f32cd2c
Create Date: 2026-10-06 06:54:47.991966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73a64f0afdcc'
down_revision: Union[str, Sequence[str], None] = '815c2f32cd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_operations',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_operations_shop_created', 'sync_operations', ['shop_id', 'created_at'], unique=False)
    op.create_index('ix_sync_operations_shop_entity', 'sync_operations', ['shop_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('sync_changes',
    sa.Column('sequence', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['sync_operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index('ix_sync_changes_shop_sequence', 'sync_changes', ['shop_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_changes_shop_sequence', table_name='sync_changes')
    op.drop_table('sync_changes')
    op.drop_index('ix_sync_operations_shop_entity', table_name='sync_operations')
    op.drop_index('ix_sync_operations_shop_created', table_name='sync_operations')
    op.drop_table('sync_operations')
    # ### end Alembic commands ###
