"""create initial domain tables

Revision ID: 815c2f32cd2c
Revises: 
Create Date: 2026-10-05 08:19:35.500256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815c2f32cd2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'phone', name='uq_customers_shop_phone')
    )
    op.create_index(op.f('ix_customers_shop_id'), 'customers', ['shop_id'], unique=False)
    op.create_table('devices',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_shop_id'), 'devices', ['shop_id'], unique=False)
    op.create_table('items',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_shop_id'), 'items', ['shop_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('UDHAAR', 'PAYMENT', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_customer_id'), 'ledger_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_device_id'), 'ledger_entries', ['device_id'], unique=False)
    op.create_table('entry_items',
    sa.Column('ledger_entry_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_entry_items_amount_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_items_item_id'), 'entry_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_entry_items_ledger_entry_id'), 'entry_items', ['ledger_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f("ix_entry_items_ledger_entry_id"),
        table_name="entry_items",
    )
    op.drop_index(
        op.f("ix_entry_items_item_id"),
        table_name="entry_items",
    )
    op.drop_table("entry_items")

    op.drop_index(
        op.f("ix_ledger_entries_device_id"),
        table_name="ledger_entries",
    )
    op.drop_index(
        op.f("ix_ledger_entries_customer_id"),
        table_name="ledger_entries",
    )
    op.drop_table("ledger_entries")

    # PostgreSQL enum is a separate database object.
    sa.Enum(
        "UDHAAR",
        "PAYMENT",
        name="ledger_entry_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    op.drop_index(
        op.f("ix_items_shop_id"),
        table_name="items",
    )
    op.drop_table("items")

    op.drop_index(
        op.f("ix_devices_shop_id"),
        table_name="devices",
    )
    op.drop_table("devices")

    op.drop_index(
        op.f("ix_customers_shop_id"),
        table_name="customers",
    )
    op.drop_table("customers")

    op.drop_table("shops")
