"""allow null entry item amount

Revision ID: 960d69879b1c
Revises: 73a64f0afdcc
Create Date: 2026-10-07 09:41:09.134302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960d69879b1c'
down_revision: Union[str, Sequence[str], None] = '73a64f0afdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_items', 'amount',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_items', 'amount',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
